CREATE TABLE [dbo].[companies] (
    [CompanyID]                   INT              IDENTITY (1, 1) NOT NULL,
    [CompanyCode]                 NVARCHAR (50)    NULL,
    [CompanyName]                 NVARCHAR (100)   NOT NULL,
    [CompanyType]                 VARCHAR (30)     NULL,
    [ParentCompanyID]             INT              NULL,
    [CompanyWebsite]              VARCHAR (100)    NULL,
    [CompanyEmail]                NVARCHAR (100)   NULL,
    [DefaultAddressID]            INT              NULL,
    [IATACode]                    VARCHAR (50)     NULL,
    [InvoiceName]                 NVARCHAR (100)   NULL,
    [TaxID]                       NVARCHAR (100)   NULL,
    [TaxOfficeName]               NVARCHAR (100)   NULL,
    [EstimatedVolume]             DECIMAL (18, 4)  NULL,
    [ProfitMargin]                DECIMAL (18, 4)  NULL,
    [CreditLimit]                 DECIMAL (18, 4)  NULL,
    [Currency]                    VARCHAR (30)     NULL,
    [PaymentMode]                 VARCHAR (30)     NULL,
    [OfficeID]                    INT              NULL,
    [CreatedBy]                   INT              NULL,
    [CreatedDate]                 DATETIME         NULL,
    [ModifiedDate]                DATETIME         NULL,
    [ModifiedBy]                  INT              NULL,
    [isDeleted]                   BIT              NULL,
    [DueDateMeans]                NVARCHAR (100)   NULL,
    [LeadTime]                    NVARCHAR (10)    NULL,
    [VATTIN]                      NVARCHAR (50)    NULL,
    [CSTNo]                       NVARCHAR (50)    NULL,
    [ExciseRegnNo]                NVARCHAR (50)    NULL,
    [Division]                    NVARCHAR (50)    NULL,
    [Range]                       NVARCHAR (50)    NULL,
    [rowguid]                     UNIQUEIDENTIFIER NOT NULL,
    [DefaultCurrency]             VARCHAR (30)     NULL,
    [Hundi]                       DECIMAL (18, 4)  NULL,
    [BrandName]                   NVARCHAR (500)   NULL,
    [Type]                        NVARCHAR (100)   NULL,
    [YearOfIncorporation]         INT              NULL,
    [BusinessConstitution]        NVARCHAR (100)   NULL,
    [PAN]                         NVARCHAR (20)    NULL,
    [TAN]                         NVARCHAR (20)    NULL,
    [DeliveryTerms]               NVARCHAR (20)    NULL,
    [ProductionLeadTime]          NVARCHAR (20)    NULL,
    [TransitTime]                 NVARCHAR (20)    NULL,
    [AgreementDate]               DATETIME         NULL,
    [CommisionRate]               DECIMAL (18, 2)  NULL,
    [SeparateShipmentPerPartType] BIT              NULL,
    [BincludePakCost]             BIT              NULL,
    [Nperpluspack]                DECIMAL (18, 2)  NULL,
    [tin]                         VARCHAR (50)     NULL,
    [BCustomerPartPackaging]      BIT              NULL,
    [ExtraCharge]                 DECIMAL (18, 2)  NULL,
    [Approved]                    BIT              NULL,
    [IsOPEPApprove]               BIT              NULL
);

