CREATE TABLE [dbo].[MasterUser] (
    [UserId]            INT           IDENTITY (1, 1) NOT NULL,
    [FirstName]         VARCHAR (255) NOT NULL,
    [LastName]          VARCHAR (255) NOT NULL,
    [LoginId]           VARCHAR (255) NULL,
    [Password]          VARCHAR (400) NULL,
    [Age]               INT           NULL,
    [MobileNo]          VARCHAR (15)  NOT NULL,
    [Email]             VARCHAR (100) NOT NULL,
    [DateOfBirth]       DATETIME      NOT NULL,
    [GenderId]          INT           NOT NULL,
    [UserType]          VARCHAR (50)  NULL,
    [GlobalId]          INT           NULL,
    [HomeTownAddress]   VARCHAR (455) NULL,
    [CountryId]         INT           NOT NULL,
    [StateId]           INT           NOT NULL,
    [CityId]            INT           NOT NULL,
    [OfficeId]          INT           NULL,
    [PinCode]           INT           NULL,
    [UserImagepath]     VARCHAR (255) NULL,
    [AdharImagepath]    VARCHAR (255) NULL,
    [PanImagepath]      VARCHAR (255) NULL,
    [CreateDate]        DATETIME      NOT NULL,
    [ModifyDate]        DATETIME      NULL,
    [IsActive]          BIT           NULL,
    [IsDeleted]         BIT           NULL,
    [CreatedBy]         INT           NOT NULL,
    [DeletedBy]         INT           NULL,
    [IsCheckedByAdmin]  BIT           NULL,
    [Modified_By]       INT           NULL,
    [DeletedDate]       DATETIME      NULL,
    [PassCode]          INT           NULL,
    [CompanyName]       VARCHAR (200) NULL,
    [LastLogin]         DATETIME      NULL,
    [TODOCheck]         DATETIME      NULL,
    [ctime_Stamp]       DATETIME      NULL,
    [OTP]               VARCHAR (10)  NULL,
    [IsMFA]             BIT           NULL,
    [MFADays]           INT           NULL,
    [MFADate]           DATETIME      NULL,
    [TermsAcceptedDate] DATETIME      NULL,
    PRIMARY KEY CLUSTERED ([UserId] ASC)
);

