CREATE TABLE [dbo].[PendingSalesOrderSync] (
    [isSELECT]              BIT             NULL,
    [FileID]                INT             NULL,
    [OrderImportFileLineID] INT             NULL,
    [PartID]                INT             NULL,
    [PartNo]                NVARCHAR (100)  NULL,
    [PartDescription]       NVARCHAR (500)  NULL,
    [DueDate]               DATETIME        NULL,
    [SupplierDueDate]       DATETIME        NULL,
    [PONumber]              VARCHAR (100)   NULL,
    [SupplierID]            INT             NULL,
    [SupplierName]          NVARCHAR (2000) NULL,
    [CompanyID]             INT             NOT NULL,
    [CompanyName]           NVARCHAR (100)  NULL,
    [ShiptoUnitName]        NVARCHAR (100)  NULL,
    [POQTY]                 INT             NULL,
    [ShippedQty]            INT             NULL,
    [InHandQTY]             DECIMAL (38, 2) NULL,
    [RejectedQTY]           DECIMAL (38, 2) NULL,
    [PendingQTY]            INT             NULL,
    [ShortageQTY]           INT             NULL,
    [PID]                   INT             NULL,
    [QTYOrdered]            INT             NULL,
    [Price]                 DECIMAL (18, 4) NULL,
    [Currency]              VARCHAR (10)    NULL,
    [TransitTime]           NVARCHAR (10)   NULL,
    [ImpexPONumber]         NVARCHAR (MAX)  NULL,
    [isParent]              INT             NOT NULL,
    [parentLineItemID]      INT             NOT NULL,
    [OrderType]             VARCHAR (30)    NULL,
    [ShipToLocation]        NVARCHAR (100)  NULL,
    [HSN]                   INT             NULL,
    [Category]              VARCHAR (20)    NULL,
    [LatestAction]          VARCHAR (20)    NULL,
    [Del_Flag]              BIT             NULL
);

