CREATE TABLE [dbo].[WarehouseReceiptsSync] (
    [POID]                  INT             NULL,
    [PartNo]                NVARCHAR (50)   NULL,
    [PODate]                DATETIME        NULL,
    [SupplierID]            INT             NULL,
    [CompanyID]             INT             NULL,
    [AddressID]             INT             NULL,
    [SupplierName]          NVARCHAR (100)  NULL,
    [SupplierPrintAs]       NVARCHAR (MAX)  NULL,
    [PONumber]              NVARCHAR (30)   NULL,
    [ReceiptID]             INT             NOT NULL,
    [ReceiptLineItemID]     INT             NULL,
    [ReceiptNo]             NVARCHAR (30)   NULL,
    [SupplierInvoiceNo]     NVARCHAR (30)   NULL,
    [SupplierInvoiceDate]   DATETIME        NULL,
    [TotalPackageCount]     INT             NULL,
    [Transporter]           NVARCHAR (30)   NULL,
    [DriverName]            NVARCHAR (30)   NULL,
    [DriverContactNo]       NVARCHAR (20)   NULL,
    [LRNo]                  NVARCHAR (50)   NULL,
    [LRDate]                DATETIME        NULL,
    [ReceivedBy]            INT             NULL,
    [ReceiptDate]           DATETIME        NULL,
    [CheckedBy]             INT             NULL,
    [CheckedDate]           DATETIME        NULL,
    [InvoiceAmount]         DECIMAL (18, 2) NULL,
    [Excise]                DECIMAL (18, 2) NULL,
    [TCS]                   DECIMAL (18, 2) NULL,
    [EdCess]                DECIMAL (18, 2) NULL,
    [HedCess]               DECIMAL (18, 2) NULL,
    [AgForm]                BIT             NULL,
    [VehicleNo]             NVARCHAR (100)  NULL,
    [ModifiedBy]            INT             NULL,
    [ModifiedDate]          DATETIME        NULL,
    [REMARK]                NVARCHAR (500)  NULL,
    [VatPercent]            DECIMAL (18, 2) NULL,
    [VatAmount]             DECIMAL (18, 2) NULL,
    [FinalInvoiceAmount]    DECIMAL (18, 2) NULL,
    [QCPerformedByid]       NVARCHAR (50)   NULL,
    [QCDateTime]            DATETIME        NULL,
    [QCRemarks]             NVARCHAR (20)   NULL,
    [QCPerformedBy]         NVARCHAR (100)  NULL,
    [ReceivedQty]           DECIMAL (38, 2) NULL,
    [DocumentsReceived]     BIT             NULL,
    [PartPrice]             DECIMAL (18, 2) NULL,
    [AcceptedQty]           DECIMAL (38, 2) NULL,
    [RejectedQty]           DECIMAL (18, 2) NULL,
    [IsATA]                 BIT             NULL,
    [SAC_Code]              VARCHAR (10)    NULL,
    [DeliveryTerm]          VARCHAR (30)    NULL,
    [VehicleType]           VARCHAR (100)   NULL,
    [MathadiCharges]        DECIMAL (18, 2) NULL,
    [PickUpPoint]           VARCHAR (500)   NULL,
    [TransportationCharges] DECIMAL (18, 2) NULL,
    [MathadiDate]           DATE            NULL,
    [MathadiReceiptNo]      VARCHAR (50)    NULL,
    [CustomerName]          NVARCHAR (100)  NULL,
    [LatestAction]          VARCHAR (20)    NULL,
    [FTPLink]               VARCHAR (200)   NULL,
    [FileName]              VARCHAR (100)   NULL,
    [isDeleted]             BIT             NULL,
    [Reasonfordelete]       VARCHAR (500)   NULL
);

